name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: iconic21/farmerapp:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}  
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: curl -X POST "https://api.digitalocean.com/v2/apps/${{ secrets.CURL_APP_ID }}/deployments" -H "${{ secrets.CURL_HEADER }}" -d "${{ secrets.CURL_BODY }}"
    
